language: b2g

compiler:
  - gcc

before_install:

script:
  - make

after_success:

cache:
  directories:
    - src

addons:
  artifacts:
    s3_region: "ap-northeast-1"
    paths:
      - hello
      - $(ls *.o | tr "\n" ":")

notifications:
  email:
    recipients:
      - seinlin.li@acadine.com
    on_success: always 
