language: b2g

compiler:
  - gcc

before_install:
  - echo 'before scripts'

script:
  - echo 'build scripts'
  - make

after_success:
  - echo 'after scripts'

cache:
  directories:
    - src

addons:
  artifacts:
    s3_region: "ap-northeast-1"
    paths:
      - hello
      - $(ls *.o | tr "\n" ":")

notifications:
  email:
    recipients:
      - owen.ouyang@acadine.com
    on_success: always
