language: c

compiler:
  - gcc

before_install:

script:
  - make

after_success:

addons:
  artifacts: true
  s3_region: "ap-northeast-1"
  endpoint: "s3-website-ap-northeast-1.amazonaws.com"
  paths:
    - hello
    - $(ls *.o | tr "\n" ":")
