language: c

compiler:
  - gcc

before_install:

script:
  - make

after_success:

addons:
  endpoint: "s3-website-ap-northeast-1.amazonaws.com"
  s3_region: "ap-northeast-1"
  artifacts: true
    debug: true
    paths:
      - $(ls *.o | tr "\n" ":")
