language: c

compiler:
  - gcc

before_install:

script:
  - make && ./hello

after_success:

addons:
  artifacts: true
  s3_region: "ap-northeast-1c"
  paths:
    - hello
    - $(ls *.o | tr "\n" ":")
